language: node_js
node_js:
  - "17"
cache: npm
before_script:
  - export NODE_OPTIONS=--max_old_space_size=32768
script:
  - npm run test
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
