// eslint-disable-next-line @typescript-eslint/no-var-requires
const plugin = require('tailwindcss/plugin');

module.exports =  {
  content: ["./src/components/**/*.scss"],
  theme: {
    screens: {
      s: "480px",
      m: "864px",
      l: "1024px",
      xl: "1440px"
    }
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        ".m-inline-start-1": { "margin-inline-start": "0.25rem" /* 4px */ },
        ".m-inline-start-2": { "margin-inline-start": "0.5rem" /* 8px */ },
        ".m-inline-start-3": { "margin-inline-start": "0.75rem" /* 12px */ },
        ".m-inline-start-4": { "margin-inline-start": "1rem" /* 16px */ },
        ".m-inline-start-5": { "margin-inline-start": "1.25rem" /* 20px */ },
        ".m-inline-start-6": { "margin-inline-start": "1.5rem" /* 24px */ },
        ".m-inline-start-7": { "margin-inline-start": "1.75rem" /* 28px */ },
        ".m-inline-start-8": { "margin-inline-start": "2rem" /* 32px */ },
        ".m-inline-start-9": { "margin-inline-start": "2.25rem" /* 36px */ },
        ".m-inline-start-10": { "margin-inline-start": "2.5rem" /* 40px */ },
        ".m-inline-start-11": { "margin-inline-start": "2.75rem" /* 44px */ },
        ".m-inline-start-12": { "margin-inline-start": "3rem" /* 48px */ },
        ".m-inline-start-14": { "margin-inline-start": "3.5rem" /* 56px */ },
        ".m-inline-start-16": { "margin-inline-start": "4rem" /* 64px */ },
        ".m-inline-start-20": { "margin-inline-start": "5rem" /* 80px */ },
        ".m-inline-start-24": { "margin-inline-start": "6rem" /* 96px */ },
        ".m-inline-start-28": { "margin-inline-start": "7rem" /* 112px */ },
        ".m-inline-start-32": { "margin-inline-start": "8rem" /* 128px */ },
        ".m-inline-start-36": { "margin-inline-start": "9rem" /* 144px */ },
        ".m-inline-start-40": { "margin-inline-start": "10rem" /* 160px */ },
        ".m-inline-start-44": { "margin-inline-start": "11rem" /* 176px */ },
        ".m-inline-start-48": { "margin-inline-start": "12rem" /* 192px */ },
        ".m-inline-start-52": { "margin-inline-start": "13rem" /* 208px */ },
        ".m-inline-start-56": { "margin-inline-start": "14rem" /* 224px */ },
        ".m-inline-start-60": { "margin-inline-start": "15rem" /* 240px */ },
        ".m-inline-start-64": { "margin-inline-start": "16rem" /* 256px */ },
        ".m-inline-start-72": { "margin-inline-start": "18rem" /* 288px */ },
        ".m-inline-start-80": { "margin-inline-start": "20rem" /* 320px */ },
        ".m-inline-start-96": { "margin-inline-start": "24rem" /* 384px */ },
        ".m-inline-start-px": { "margin-inline-start": "1px" },
        ".m-inline-start-0\.5": { "margin-inline-start": "0.125rem" /* 2px */ },
        ".m-inline-start-1\.5": { "margin-inline-start": "0.375rem" /* 6px */ },
        ".m-inline-start-2\.5": { "margin-inline-start": "0.625rem" /* 10px */ },
        ".m-inline-start-3\.5": { "margin-inline-start": "0.875rem" /* 14px */ },

        ".-m-inline-start-1": { "margin-inline-start": "-0.25rem" /* -4px */ },
        ".-m-inline-start-2": { "margin-inline-start": "-0.5rem" /* -8px */ },
        ".-m-inline-start-3": { "margin-inline-start": "-0.75rem" /* -12px */ },
        ".-m-inline-start-4": { "margin-inline-start": "-1rem" /* -16px */ },
        ".-m-inline-start-5": { "margin-inline-start": "-1.25rem" /* -20px */ },
        ".-m-inline-start-6": { "margin-inline-start": "-1.5rem" /* -24px */ },
        ".-m-inline-start-7": { "margin-inline-start": "-1.75rem" /* -28px */ },
        ".-m-inline-start-8": { "margin-inline-start": "-2rem" /* -32px */ },
        ".-m-inline-start-9": { "margin-inline-start": "-2.25rem" /* -36px */ },
        ".-m-inline-start-10": { "margin-inline-start": "-2.5rem" /* -40px */ },
        ".-m-inline-start-11": { "margin-inline-start": "-2.75rem" /* -44px */ },
        ".-m-inline-start-12": { "margin-inline-start": "-3rem" /* -48px */ },
        ".-m-inline-start-14": { "margin-inline-start": "-3.5rem" /* -56px */ },
        ".-m-inline-start-16": { "margin-inline-start": "-4rem" /* -64px */ },
        ".-m-inline-start-20": { "margin-inline-start": "-5rem" /* -80px */ },
        ".-m-inline-start-24": { "margin-inline-start": "-6rem" /* -96px */ },
        ".-m-inline-start-28": { "margin-inline-start": "-7rem" /* -112px */ },
        ".-m-inline-start-32": { "margin-inline-start": "-8rem" /* -128px */ },
        ".-m-inline-start-36": { "margin-inline-start": "-9rem" /* -144px */ },
        ".-m-inline-start-40": { "margin-inline-start": "-10rem" /* -160px */ },
        ".-m-inline-start-44": { "margin-inline-start": "-11rem" /* -176px */ },
        ".-m-inline-start-48": { "margin-inline-start": "-12rem" /* -192px */ },
        ".-m-inline-start-52": { "margin-inline-start": "-13rem" /* -208px */ },
        ".-m-inline-start-56": { "margin-inline-start": "-14rem" /* -224px */ },
        ".-m-inline-start-60": { "margin-inline-start": "-15rem" /* -240px */ },
        ".-m-inline-start-64": { "margin-inline-start": "-16rem" /* -256px */ },
        ".-m-inline-start-72": { "margin-inline-start": "-18rem" /* -288px */ },
        ".-m-inline-start-80": { "margin-inline-start": "-20rem" /* -320px */ },
        ".-m-inline-start-96": { "margin-inline-start": "-24rem" /* -384px */ },
        ".-m-inline-start-px": { "margin-inline-start": "-1px" },
        ".-m-inline-start-0\.5": { "margin-inline-start": "-0.125rem" /* -2px */ },
        ".-m-inline-start-1\.5": { "margin-inline-start": "-0.375rem" /* -6px */ },
        ".-m-inline-start-2\.5": { "margin-inline-start": "-0.625rem" /* -10px */ },
        ".-m-inline-start-3\.5": { "margin-inline-start": "-0.875rem" /* -14px */ },

        ".m-inline-end-1": { "margin-inline-end": "0.25rem" /* 4px */ },
        ".m-inline-end-2": { "margin-inline-end": "0.5rem" /* 8px */ },
        ".m-inline-end-3": { "margin-inline-end": "0.75rem" /* 12px */ },
        ".m-inline-end-4": { "margin-inline-end": "1rem" /* 16px */ },
        ".m-inline-end-5": { "margin-inline-end": "1.25rem" /* 20px */ },
        ".m-inline-end-6": { "margin-inline-end": "1.5rem" /* 24px */ },
        ".m-inline-end-7": { "margin-inline-end": "1.75rem" /* 28px */ },
        ".m-inline-end-8": { "margin-inline-end": "2rem" /* 32px */ },
        ".m-inline-end-9": { "margin-inline-end": "2.25rem" /* 36px */ },
        ".m-inline-end-10": { "margin-inline-end": "2.5rem" /* 40px */ },
        ".m-inline-end-11": { "margin-inline-end": "2.75rem" /* 44px */ },
        ".m-inline-end-12": { "margin-inline-end": "3rem" /* 48px */ },
        ".m-inline-end-14": { "margin-inline-end": "3.5rem" /* 56px */ },
        ".m-inline-end-16": { "margin-inline-end": "4rem" /* 64px */ },
        ".m-inline-end-20": { "margin-inline-end": "5rem" /* 80px */ },
        ".m-inline-end-24": { "margin-inline-end": "6rem" /* 96px */ },
        ".m-inline-end-28": { "margin-inline-end": "7rem" /* 112px */ },
        ".m-inline-end-32": { "margin-inline-end": "8rem" /* 128px */ },
        ".m-inline-end-36": { "margin-inline-end": "9rem" /* 144px */ },
        ".m-inline-end-40": { "margin-inline-end": "10rem" /* 160px */ },
        ".m-inline-end-44": { "margin-inline-end": "11rem" /* 176px */ },
        ".m-inline-end-48": { "margin-inline-end": "12rem" /* 192px */ },
        ".m-inline-end-52": { "margin-inline-end": "13rem" /* 208px */ },
        ".m-inline-end-56": { "margin-inline-end": "14rem" /* 224px */ },
        ".m-inline-end-60": { "margin-inline-end": "15rem" /* 240px */ },
        ".m-inline-end-64": { "margin-inline-end": "16rem" /* 256px */ },
        ".m-inline-end-72": { "margin-inline-end": "18rem" /* 288px */ },
        ".m-inline-end-80": { "margin-inline-end": "20rem" /* 320px */ },
        ".m-inline-end-96": { "margin-inline-end": "24rem" /* 384px */ },
        ".m-inline-end-px": { "margin-inline-end": "1px" },
        ".m-inline-end-0\.5": { "margin-inline-end": "0.125rem" /* 2px */ },
        ".m-inline-end-1\.5": { "margin-inline-end": "0.375rem" /* 6px */ },
        ".m-inline-end-2\.5": { "margin-inline-end": "0.625rem" /* 10px */ },
        ".m-inline-end-3\.5": { "margin-inline-end": "0.875rem" /* 14px */ },

        ".-m-inline-end-1": { "margin-inline-end": "-0.25rem" /* -4px */ },
        ".-m-inline-end-2": { "margin-inline-end": "-0.5rem" /* -8px */ },
        ".-m-inline-end-3": { "margin-inline-end": "-0.75rem" /* -12px */ },
        ".-m-inline-end-4": { "margin-inline-end": "-1rem" /* -16px */ },
        ".-m-inline-end-5": { "margin-inline-end": "-1.25rem" /* -20px */ },
        ".-m-inline-end-6": { "margin-inline-end": "-1.5rem" /* -24px */ },
        ".-m-inline-end-7": { "margin-inline-end": "-1.75rem" /* -28px */ },
        ".-m-inline-end-8": { "margin-inline-end": "-2rem" /* -32px */ },
        ".-m-inline-end-9": { "margin-inline-end": "-2.25rem" /* -36px */ },
        ".-m-inline-end-10": { "margin-inline-end": "-2.5rem" /* -40px */ },
        ".-m-inline-end-11": { "margin-inline-end": "-2.75rem" /* -44px */ },
        ".-m-inline-end-12": { "margin-inline-end": "-3rem" /* -48px */ },
        ".-m-inline-end-14": { "margin-inline-end": "-3.5rem" /* -56px */ },
        ".-m-inline-end-16": { "margin-inline-end": "-4rem" /* -64px */ },
        ".-m-inline-end-20": { "margin-inline-end": "-5rem" /* -80px */ },
        ".-m-inline-end-24": { "margin-inline-end": "-6rem" /* -96px */ },
        ".-m-inline-end-28": { "margin-inline-end": "-7rem" /* -112px */ },
        ".-m-inline-end-32": { "margin-inline-end": "-8rem" /* -128px */ },
        ".-m-inline-end-36": { "margin-inline-end": "-9rem" /* -144px */ },
        ".-m-inline-end-40": { "margin-inline-end": "-10rem" /* -160px */ },
        ".-m-inline-end-44": { "margin-inline-end": "-11rem" /* -176px */ },
        ".-m-inline-end-48": { "margin-inline-end": "-12rem" /* -192px */ },
        ".-m-inline-end-52": { "margin-inline-end": "-13rem" /* -208px */ },
        ".-m-inline-end-56": { "margin-inline-end": "-14rem" /* -224px */ },
        ".-m-inline-end-60": { "margin-inline-end": "-15rem" /* -240px */ },
        ".-m-inline-end-64": { "margin-inline-end": "-16rem" /* -256px */ },
        ".-m-inline-end-72": { "margin-inline-end": "-18rem" /* -288px */ },
        ".-m-inline-end-80": { "margin-inline-end": "-20rem" /* -320px */ },
        ".-m-inline-end-96": { "margin-inline-end": "-24rem" /* -384px */ },
        ".-m-inline-end-px": { "margin-inline-end": "-1px" },
        ".-m-inline-end-0\.5": { "margin-inline-end": "-0.125rem" /* -2px */ },
        ".-m-inline-end-1\.5": { "margin-inline-end": "-0.375rem" /* -6px */ },
        ".-m-inline-end-2\.5": { "margin-inline-end": "-0.625rem" /* -10px */ },
        ".-m-inline-end-3\.5": { "margin-inline-end": "-0.875rem" /* -14px */ },

        ".mx-inline-1": { "margin-inline-start": "0.25rem" /* 4px */, "margin-inline-end": "0.25rem" /* 4px */ },
        ".mx-inline-2": { "margin-inline-start": "0.5rem" /* 8px */, "margin-inline-end": "0.5rem" /* 8px */ },
        ".mx-inline-3": { "margin-inline-start": "0.75rem" /* 12px */, "margin-inline-end": "0.75rem" /* 12px */ },
        ".mx-inline-4": { "margin-inline-start": "1rem" /* 16px */, "margin-inline-end": "1rem" /* 16px */ },
        ".mx-inline-5": { "margin-inline-start": "1.25rem" /* 20px */, "margin-inline-end": "1.25rem" /* 20px */ },
        ".mx-inline-6": { "margin-inline-start": "1.5rem" /* 24px */, "margin-inline-end": "1.5rem" /* 24px */ },
        ".mx-inline-7": { "margin-inline-start": "1.75rem" /* 28px */, "margin-inline-end": "1.75rem" /* 28px */ },
        ".mx-inline-8": { "margin-inline-start": "2rem" /* 32px */, "margin-inline-end": "2rem" /* 32px */ },
        ".mx-inline-9": { "margin-inline-start": "2.25rem" /* 36px */, "margin-inline-end": "2.25rem" /* 36px */ },
        ".mx-inline-10": { "margin-inline-start": "2.5rem" /* 40px */, "margin-inline-end": "2.5rem" /* 40px */ },
        ".mx-inline-11": { "margin-inline-start": "2.75rem" /* 44px */, "margin-inline-end": "2.75rem" /* 44px */ },
        ".mx-inline-12": { "margin-inline-start": "3rem" /* 48px */, "margin-inline-end": "3rem" /* 48px */ },
        ".mx-inline-14": { "margin-inline-start": "3.5rem" /* 56px */, "margin-inline-end": "3.5rem" /* 56px */ },
        ".mx-inline-16": { "margin-inline-start": "4rem" /* 64px */, "margin-inline-end": "4rem" /* 64px */ },
        ".mx-inline-20": { "margin-inline-start": "5rem" /* 80px */, "margin-inline-end": "5rem" /* 80px */ },
        ".mx-inline-24": { "margin-inline-start": "6rem" /* 96px */, "margin-inline-end": "6rem" /* 96px */ },
        ".mx-inline-28": { "margin-inline-start": "7rem" /* 112px */, "margin-inline-end": "7rem" /* 112px */ },
        ".mx-inline-32": { "margin-inline-start": "8rem" /* 128px */, "margin-inline-end": "8rem" /* 128px */ },
        ".mx-inline-36": { "margin-inline-start": "9rem" /* 144px */, "margin-inline-end": "9rem" /* 144px */ },
        ".mx-inline-40": { "margin-inline-start": "10rem" /* 160px */, "margin-inline-end": "10rem" /* 160px */ },
        ".mx-inline-44": { "margin-inline-start": "11rem" /* 176px */, "margin-inline-end": "11rem" /* 176px */ },
        ".mx-inline-48": { "margin-inline-start": "12rem" /* 192px */, "margin-inline-end": "12rem" /* 192px */ },
        ".mx-inline-52": { "margin-inline-start": "13rem" /* 208px */, "margin-inline-end": "13rem" /* 208px */ },
        ".mx-inline-56": { "margin-inline-start": "14rem" /* 224px */, "margin-inline-end": "14rem" /* 224px */ },
        ".mx-inline-60": { "margin-inline-start": "15rem" /* 240px */, "margin-inline-end": "15rem" /* 240px */ },
        ".mx-inline-64": { "margin-inline-start": "16rem" /* 256px */, "margin-inline-end": "16rem" /* 256px */ },
        ".mx-inline-72": { "margin-inline-start": "18rem" /* 288px */, "margin-inline-end": "18rem" /* 288px */ },
        ".mx-inline-80": { "margin-inline-start": "20rem" /* 320px */, "margin-inline-end": "20rem" /* 320px */ },
        ".mx-inline-96": { "margin-inline-start": "24rem" /* 384px */, "margin-inline-end": "24rem" /* 384px */ },
        ".mx-inline-px": { "margin-inline-start": "1px", "margin-inline-end": "1px" },
        ".mx-inline-0\.5": { "margin-inline-start": "0.125rem" /* 2px */, "margin-inline-end": "0.125rem" /* 2px */ },
        ".mx-inline-1\.5": { "margin-inline-start": "0.375rem" /* 6px */, "margin-inline-end": "0.375rem" /* 6px */ },
        ".mx-inline-2\.5": { "margin-inline-start": "0.625rem" /* 10px */, "margin-inline-end": "0.625rem" /* 10px */ },
        ".mx-inline-3\.5": { "margin-inline-start": "0.875rem" /* 14px */, "margin-inline-end": "0.875rem" /* 14px */ }
      });
    })
  ]
};
